apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx
  namespace: kafka-monitoring
  labels:
    app: kafka-jmx
spec:
  ports:
    - name: jmx-metrics
      port: 7071
      targetPort: 7071
      protocol: TCP
