apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-jmx
  namespace: kafka-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kafka-jmx
  endpoints:
    - port: jmx-metrics
      interval: 30s
      path: /metrics

