apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-jmx
  namespace: monitoring
  labels:
    app: kafka-jmx

subsets:
  - addresses:
      - ip: <KAFKA_BROKER_3_IP>
        hostname: lnx-crp-shdsvc-bkr-qa-usea-003

    ports:
      - name: metrics
        port: 7071
        protocol: TCP