apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-jmx
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kafka-jmx

  namespaceSelector:
    matchNames:
      - monitoring

  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics